# Generated by Django 3.1.2 on 2020-10-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201022_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('solid', 'solid'), ('dotted', 'dotted'), ('none', 'none')], default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('blue', 'blue'), ('red', 'red')], default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Times New Roman', 'Times New Roman'), ('Helvetica', 'Helvetica'), ('Open Sans', 'Open Sans')], default='', max_length=100, null=True),
        ),
    ]
