# Generated by Django 3.1.2 on 2020-10-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='friends',
        ),
        migrations.AddField(
            model_name='follow',
            name='followed_users',
            field=models.ManyToManyField(null=True, related_name='_follow_followed_users_+', to='api.Follow'),
        ),
    ]
