# Generated by Django 3.1.2 on 2020-10-26 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20201026_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='accepting_user',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='proposing_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendrequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
