# Generated by Django 3.1.2 on 2020-10-27 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20201026_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='FollowedUsers',
        ),
    ]
