# Generated by Django 3.1.2 on 2020-10-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201027_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
