# Generated by Django 3.1.2 on 2020-10-27 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedusers',
            name='proposing_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
