# Generated by Django 3.1.2 on 2020-10-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201027_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followedusers',
            options={'verbose_name': 'followed user'},
        ),
    ]
