# Generated by Django 3.1.2 on 2020-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201028_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('none', 'none'), ('', '')], default='', max_length=100, null=True),
        ),
    ]
